swagger: '2.0'

info:
  version: "0.1"
  title: even
  description: SSH access granting service

basePath: /

consumes:
  - application/json
produces:
  - application/json

definitions:
  AccessRequest:
    required:
      - hostname
      - reason
    properties:
      username:
        type: string
        description: A valid POSIX user name
        pattern: "^[a-z][a-z0-9-]{0,31}$"
        example: jdoe
      hostname:
        type: string
        description: A valid FQDN or IP address
        pattern: "^[a-z0-9.-]{0,255}$"
        example: my-host.example.org
      reason:
        type: string
        description: The request reason
        example: Troubleshoot problem XY
      remote-host:
        type: string
        description: A valid FQDN or IP address
        pattern: "^[a-z0-9.-]{0,255}$"

paths:
  /public-keys/{name}/sshkey.pub:
    get:
      description: Download public SSH key
      operationId: org.zalando.stups.even.api/serve-public-key
      parameters:
        - name: name
          in: path
          description: User name
          required: true
          type: string
          pattern: "^[a-z][a-z0-9-]{0,31}$"
      produces:
        - text/plain
      responses:
        200:
          description: |
            Return public SSH key as string, usable for authorized_keys file of OpenSSH.
          schema:
            type: string
            title: PublicSshKey
        404:
          description: User and/or his SSH key cannot be found
        400:
          description: Invalid username parameter


  /access-requests:
    post:
      description: |
       Request SSH access to a single host
      operationId: org.zalando.stups.even.api/request-access
      parameters:
        # An example parameter that is in query and is required
        - name: request
          in: body
          description: Access Request
          required: true
          schema:
            $ref: "#/definitions/AccessRequest"

      # Expected responses for this operation:
      responses:
        # Response code
        200:
          description: Successful response
          # A schema describing your response object.
          # Use JSON Schema format
          schema:
            title: SuccessMessage
            type: string
            example: Access to host XY for user ABC was granted.
